name: Deploy to Vercel
on:
  push:
    branches:
      - vercel-deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry from marketplace action
      - uses: snok/install-poetry@v1
      - name: Checkout action
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - run: poetry install
      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          #working-directory: ./sub-directory
