name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - vercel-deployment
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Poetry from marketplace action
        uses: snok/install-poetry@v1
      - name: Poetry install
        run: poetry install
      - name: Create output dir
        run: mkdir output
      - name: Move artifacts to vercel output dir
        run: mv freetar output/
      - name: List files in current state
        run: find .
#      - name: Create output dir
#        run: mkdir -p ~/work/freetar/freetar/build
#      - name: Build Project Artifacts
#        run: vercel --force build  --prod --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Deploy Project Artifacts to Vercel
#        run: vercel --force deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
